---
Title: Wendy Exploration MLE
author: Jack Krebsbach
format:
 typst:
    toc: true
    section-numbering: 1.1.a
---

# Wendy

Load libraries

```{r}
library(Rcpp)
library(symengine)
library(devtools)
```

## For local development sourcing cpp files

```{r}
unlink(tempdir(), recursive = TRUE)

Sys.setenv("PKG_CXXFLAGS" = "-std=c++20 -I/opt/homebrew/include -I/opt/homebrew/include/eigen3 -I/opt/homebrew/Caskroom/miniforge/base/include")
Sys.setenv("PKG_LIBS" = "-L/opt/homebrew/lib -lsymengine -lflint -lgmp -lmpfr -lfmt -lfftw3")


Rcpp::sourceCpp('exploration/pkg-dev.cpp')

loadModule('WendyRDev', TRUE)

source("R/example.R")
w <- new(WendyRDev, du, U, p_hat, matrix(tt, ncol = 1))
w$build_full_test_function_matrices()

V_full <- w$getV()
V_p <- w$getVprime()
dim(V_p)
dim(V_full)
```


## Build Package Locally

```{r}
print(getwd())
devtools::clean_dll()
devtools::document()
Rcpp::compileAttributes()
devtools::load_all()
```

## Try version from github

```{r}
devtools::install_github("jackkrebsbach/wendy.R", force = TRUE)
```

```{r}
library(WENDyMLE)
Rcpp::loadModule("WendyR")
w <- new(WendyR, du, U, p_hat, matrix(tt, ncol = 1))
w$build_test_function_matrices()
v_full <- w$getV()

```


```{r}
hes1modelODE <- function(theta, x, tvec) {
 P <- x[, 1]
 M <- x[, 2]
 H <- x[, 3]
 PMHdt <- array(0, c(nrow(x), ncol(x)))
 PMHdt[, 1] <- -theta[1] * P * H + theta[2] * M - theta[3] * P
 PMHdt[, 2] <- -theta[4] * M + theta[5] / (1 + P^2)
 PMHdt[, 3] <- -theta[1] * P * H + theta[6] / (1 + P^2) - theta[7] * H
 PMHdt
 }
```