// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SolveWendyProblem
Rcpp::List SolveWendyProblem(Rcpp::CharacterVector f, Rcpp::NumericMatrix U, Rcpp::NumericVector p0, Rcpp::NumericMatrix tt, double noise_sd, bool compute_svd_, bool optimize_, std::string dist_type);
RcppExport SEXP _wendy_SolveWendyProblem(SEXP fSEXP, SEXP USEXP, SEXP p0SEXP, SEXP ttSEXP, SEXP noise_sdSEXP, SEXP compute_svd_SEXP, SEXP optimize_SEXP, SEXP dist_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type U(USEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< double >::type noise_sd(noise_sdSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_svd_(compute_svd_SEXP);
    Rcpp::traits::input_parameter< bool >::type optimize_(optimize_SEXP);
    Rcpp::traits::input_parameter< std::string >::type dist_type(dist_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(SolveWendyProblem(f, U, p0, tt, noise_sd, compute_svd_, optimize_, dist_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wendy_SolveWendyProblem", (DL_FUNC) &_wendy_SolveWendyProblem, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_wendy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
