# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SolveWendyProblem <- function(f, U, p0, tt, log_level, compute_svd_, optimize_, dist_type) {
    .Call(`_wendy_SolveWendyProblem`, f, U, p0, tt, log_level, compute_svd_, optimize_, dist_type)
}

