# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Test <- function() {
    invisible(.Call(`_wendy_Test`))
}

SolveWendyProblem2 <- function(f, U, p0, tt, noise_sd, compute_svd_, optimize_, dist_type) {
    .Call(`_wendy_SolveWendyProblem2`, f, U, p0, tt, noise_sd, compute_svd_, optimize_, dist_type)
}

